# Generated by Django 4.1.6 on 2023-03-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='akun',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar',
            field=models.ImageField(upload_to='assets', verbose_name=''),
        ),
    ]
