# Generated by Django 4.1.6 on 2023-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_akun_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkhukum',
            name='kategori',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produkhukum',
            name='nama',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
