# Generated by Django 4.1.6 on 2023-03-17 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_akun_id_alter_berita_id_alter_paparan_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
