# Generated by Django 4.1.6 on 2023-03-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_akun_id_alter_berita_uuid_alter_paparan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='uuid',
            new_name='id',
        ),
    ]
