# Generated by Django 4.1.6 on 2023-05-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contoh1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contoh2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
    ]
