# Generated by Django 4.1.6 on 2023-05-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_contoh1_contoh2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.CharField(max_length=20)),
                ('deskripsi', models.CharField(max_length=200)),
            ],
        ),
    ]
