# Generated by Django 4.1.6 on 2023-05-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_combinedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contoh2',
            name='contoh1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contoh1'),
        ),
        migrations.AlterField(
            model_name='contoh1',
            name='isi',
            field=models.CharField(default='default value', max_length=20, null=True),
        ),
    ]
