# Generated by Django 4.1.6 on 2023-05-24 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_album_tracks_alter_album_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('instrument', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='num_star',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musician', to='base.musician'),
        ),
    ]
