# Generated by Django 4.1.6 on 2023-05-24 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_delete_album_delete_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, null=True)),
                ('instrumen', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_nama', models.CharField(max_length=200)),
                ('num_star', models.IntegerField(null=True)),
                ('artis', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_musisi', to='base.musisi')),
            ],
        ),
    ]
