# Generated by Django 4.1.6 on 2023-05-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_musisi_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('spesialis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_resep', models.CharField(max_length=50)),
                ('chef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resep_chef', to='base.chef')),
            ],
        ),
    ]
