# Generated by Django 4.1.6 on 2023-06-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_koperasi_umkm_laporankeuangan_jenisprodukumkm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenagaKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=255)),
                ('jumlah', models.IntegerField(null=True)),
                ('pendidikan', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenaga_kerja_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='PermintaanProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=255)),
                ('tahun', models.IntegerField(null=True)),
                ('nama_produk', models.CharField(max_length=255)),
                ('permintaan', models.CharField(max_length=255)),
                ('produksi', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_produk_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='PermintaanPemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=255)),
                ('tahun', models.IntegerField(null=True)),
                ('pemasok', models.CharField(max_length=255)),
                ('permintaan', models.CharField(max_length=255)),
                ('produksi', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permintaan_pemasok_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='Perijinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255)),
                ('nomor', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perijinan_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='PenilaianPemasok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemasok', models.CharField(max_length=255)),
                ('kualitas', models.CharField(max_length=255)),
                ('pengiriman', models.CharField(max_length=255)),
                ('harga', models.IntegerField(null=True)),
                ('kualitas_harga', models.IntegerField(null=True)),
                ('kualitas_pengiriman', models.IntegerField(null=True)),
                ('harga_pengiriman', models.IntegerField(null=True)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_pemasok_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='PemakaianEnergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255)),
                ('kapasitas', models.IntegerField(null=True)),
                ('keterangan', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pemakaian_energi_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tahun', models.IntegerField(null=True)),
                ('tempat', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pelatihan_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
                ('tahun', models.IntegerField(null=True)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasilitas_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='BahanBaku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=255)),
                ('volume', models.IntegerField(null=True)),
                ('nilai', models.IntegerField(null=True)),
                ('asal_bahan_baku', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bahan_baku_umkm', to='base.umkm')),
            ],
        ),
        migrations.CreateModel(
            name='AlatProduksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('umkm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alat_produksi_umkm', to='base.umkm')),
            ],
        ),
    ]
